"""Legacy experimentation helpers for irregular level packs.

Production packs are generated by the shared C# LevelGenerator through
PaintMaze.EditorTools.LevelBakeTool.BakeAll. Running this script launches that
canonical baker so runtime and bundled boards cannot drift.

Every board has an irregular exterior silhouette, raised internal walls, and a
connected paintable floor. It is also NEVER-STUCK: it satisfies the exact guarantee that
Solver.IsAlwaysSolvable checks, so the player can NEVER roll into an unsolvable
state regardless of move order. No undo/restart is ever required.

Method: carve several notches from a rectangular mask to create exterior void,
scatter walls inside the remaining footprint, then KEEP the candidate only if,
from a chosen spawn, (1) every floor cell is covered by some reachable slide path
and (2) the reachable stop-graph is strongly connected.

Outputs:
  - Assets/Resources/Levels/{easy,medium,hard,extrahard}_pack.txt  (S/./#/_ format)
  - tools/pack_preview.png  (top-down style preview of a few levels)
"""
import os, random, subprocess, sys
from collections import deque

DIRS = [(-1, 0), (1, 0), (0, -1), (0, 1)]
OUT_DIR = os.path.join(os.path.dirname(__file__), "..", "Assets", "Resources", "Levels")


# ---------- shared mechanics ----------
def slide(grid, R, C, pos, d):
    dr, dc = d; r, c = pos; path = []
    while True:
        nr, nc = r + dr, c + dc
        if not (0 <= nr < R and 0 <= nc < C) or grid[nr][nc] != 1:
            break
        r, c = nr, nc; path.append((r, c))
    return (r, c), path


def floors(grid, R, C):
    return [(r, c) for r in range(R) for c in range(C) if grid[r][c] == 1]


def connected(grid, R, C):
    fl = set(floors(grid, R, C))
    if not fl:
        return False
    s = next(iter(fl)); seen = {s}; q = deque([s])
    while q:
        r, c = q.popleft()
        for dr, dc in DIRS:
            n = (r + dr, c + dc)
            if n in fl and n not in seen:
                seen.add(n); q.append(n)
    return len(seen) == len(fl)


# ---------- the never-stuck guarantee (mirror of Solver.IsAlwaysSolvable) ----------
def always_solvable(grid, R, C, start):
    forward = {}
    reachable = {start}
    covered = {start}
    q = deque([start])
    while q:
        cur = q.popleft()
        for d in DIRS:
            stop, path = slide(grid, R, C, cur, d)
            if stop == cur:
                continue
            for p in path:
                covered.add(p)
            forward.setdefault(cur, []).append(stop)
            if stop not in reachable:
                reachable.add(stop); q.append(stop)

    # (1) coverage: every floor cell paintable by some reachable slide.
    for cell in floors(grid, R, C):
        if cell not in covered:
            return False

    # (2) strong connectivity: spawn reachable FROM every reachable node.
    reverse = {}
    for a, tos in forward.items():
        for b in tos:
            reverse.setdefault(b, []).append(a)
    back = {start}; rq = deque([start])
    while rq:
        cur = rq.popleft()
        for prev in reverse.get(cur, ()):
            if prev not in back:
                back.add(prev); rq.append(prev)
    return all(p in back for p in reachable)


# ---------- irregular + never-stuck generation ----------
# Denser (lower) wall fractions are tried first; the schedule relaxes if needed.
HF_SCHEDULE = [0.16, 0.18, 0.14, 0.20, 0.22, 0.12, 0.24, 0.26]


def irregular_mask(R, C, rng):
    """Active-cell mask made by cutting shallow rectangles from random edges."""
    mask = [[True] * C for _ in range(R)]
    cut_count = rng.randint(2, max(3, (R + C) // 3))
    for _ in range(cut_count):
        edge = rng.randrange(4)
        if edge < 2:  # top / bottom
            span = rng.randint(1, max(1, C // 3))
            depth = rng.randint(1, max(1, min(3, R // 3)))
            start = rng.randrange(0, C - span + 1)
            rows = range(depth) if edge == 0 else range(R - depth, R)
            for r in rows:
                for c in range(start, start + span):
                    mask[r][c] = False
        else:  # left / right
            span = rng.randint(1, max(1, R // 3))
            depth = rng.randint(1, max(1, min(3, C // 3)))
            start = rng.randrange(0, R - span + 1)
            cols = range(depth) if edge == 2 else range(C - depth, C)
            for r in range(start, start + span):
                for c in cols:
                    mask[r][c] = False

    # Avoid masks that are too aggressively carved.
    active = sum(1 for r in range(R) for c in range(C) if mask[r][c])
    return mask if active >= int(R * C * 0.58) else None


def gen_board(R, C, rng, hf):
    mask = irregular_mask(R, C, rng)
    if mask is None:
        return None
    grid = [[1 if mask[r][c] else -1 for c in range(C)] for r in range(R)]
    cells = [(r, c) for r in range(R) for c in range(C) if mask[r][c]]
    active = set(cells)
    target = int(round(len(cells) * hf))
    walls = set()

    # Prefer short bars over independent speckles. A small single-cell chance keeps
    # occasional compact obstacles like the references without filling the board with
    # tower-like orphans.
    attempts = 0
    while len(walls) < target and attempts < max(40, target * 16):
        attempts += 1
        r, c = rng.choice(cells)
        horizontal = rng.random() < 0.5
        length = 1 if rng.random() < 0.12 else rng.choice((2, 2, 3))
        dr, dc = (0, 1) if horizontal else (1, 0)
        if rng.random() < 0.5:
            dr, dc = -dr, -dc
        bar = [(r + dr * i, c + dc * i) for i in range(length)]
        bar = [p for p in bar if p in active]
        if not bar:
            continue
        for p in bar:
            if len(walls) >= target:
                break
            walls.add(p)

    # Retain at most a small bounded number of truly isolated walls.
    def neighbours(p):
        r, c = p
        return ((r - 1, c), (r + 1, c), (r, c - 1), (r, c + 1))

    isolated = [p for p in walls if not any(n in walls for n in neighbours(p))]
    rng.shuffle(isolated)
    keep_isolated = max(1, int(round(len(walls) * 0.15)))
    for p in isolated[keep_isolated:]:
        walls.remove(p)

    for r, c in walls:
        grid[r][c] = 0
    if not connected(grid, R, C):
        return None
    return grid


def find_board(seed, R, C, cap_per_hf=8000):
    """Return (grid, start) for a dense never-stuck board (always succeeds)."""
    rng = random.Random(seed & 0x7FFFFFFF)
    attempt = 0
    while True:  # escalate forever; in practice the first pass finds one.
        for hf in HF_SCHEDULE:
            for _ in range(cap_per_hf):
                grid = gen_board(R, C, rng, hf)
                if grid is None:
                    continue
                start = rng.choice(floors(grid, R, C))
                if always_solvable(grid, R, C, start):
                    return grid, start
        attempt += 1
        cap_per_hf *= 2  # extremely unlikely; just a safety valve.


# ---------- packaging ----------
def trim(grid, start):
    occupied = [(r, c) for r in range(len(grid)) for c in range(len(grid[0])) if grid[r][c] != -1]
    r0 = min(r for r, _ in occupied); r1 = max(r for r, _ in occupied)
    c0 = min(c for _, c in occupied); c1 = max(c for _, c in occupied)
    ng = [[grid[r][c] for c in range(c0, c1 + 1)] for r in range(r0, r1 + 1)]
    return ng, (start[0] - r0, start[1] - c0)


def to_text(grid, spawn):
    rows = []
    for r in range(len(grid)):
        rows.append("".join("S" if (r, c) == spawn else
                            ("." if grid[r][c] == 1 else ("#" if grid[r][c] == 0 else "_"))
                            for c in range(len(grid[0]))))
    return "\n".join(rows)


# width/height ranges grow across the 60 levels of each pack.
MODES = {
    "Easy":      dict(file="easy_pack.txt",      w=(6, 7),  h=(7, 8),  seed=11003),
    "Medium":    dict(file="medium_pack.txt",    w=(7, 8),  h=(8, 9),  seed=23003),
    "Hard":      dict(file="hard_pack.txt",      w=(8, 8),  h=(9, 10), seed=37003),
    "ExtraHard": dict(file="extrahard_pack.txt", w=(8, 9),  h=(10, 11), seed=51001),
}
PER_MODE = 60


def lerp_int(a, b, t):
    return int(round(a + (b - a) * t))


def build_all():
    os.makedirs(OUT_DIR, exist_ok=True)
    samples = []
    for name, cfg in MODES.items():
        blocks = []
        for i in range(1, PER_MODE + 1):
            t = (i - 1) / (PER_MODE - 1)
            W = lerp_int(cfg["w"][0], cfg["w"][1], t)
            H = lerp_int(cfg["h"][0], cfg["h"][1], t)
            seed = cfg["seed"] + i * 9176
            grid, start = find_board(seed, H, W)
            g, s = trim(grid, start)
            blocks.append(f"{name} {i}\n{to_text(g, s)}")
            if i in (4, 30):
                samples.append((f"{name} {i}", g, s))
        header = ("# %s pack - IRREGULAR + NEVER-STUCK boards, generated offline.\n"
                  "# Every board satisfies Solver.IsAlwaysSolvable: full coverage and a\n"
                  "# strongly-connected slide graph, so move order can never strand the ball.\n"
                  "# S = spawn, . = floor, # = raised wall, _ = exterior void.\n"
                  "# Blocks separated by blank lines.\n" % name)
        path = os.path.join(OUT_DIR, cfg["file"])
        with open(path, "w") as f:
            f.write(header + "\n" + "\n\n".join(blocks) + "\n")
        cells = sum(len(g[0]) * len(g) for _, g, _ in samples) or 1
        print(f"wrote {os.path.relpath(path)} ({PER_MODE} never-stuck levels)")
    return samples


def render_preview(samples, out="tools/pack_preview.png"):
    from PIL import Image, ImageDraw
    BG = (38, 43, 51); SIDE = (46, 52, 63); TILE = (140, 152, 177)
    SPAWN = (242, 184, 61); BALL = (245, 245, 240)
    cell, pad = 30, 24
    maxw = max(len(g[0]) for _, g, _ in samples)
    maxh = max(len(g) for _, g, _ in samples)
    panel_w = maxw * cell + pad * 2
    panel_h = maxh * cell + pad * 2 + 24
    img = Image.new("RGB", (panel_w * len(samples), panel_h), BG)
    d = ImageDraw.Draw(img)
    for idx, (title, g, s) in enumerate(samples):
        ox = idx * panel_w + pad; oy = pad + 22
        for r in range(len(g)):
            for c in range(len(g[0])):
                if g[r][c] != 1:
                    continue
                x0 = ox + c * cell; y0 = oy + r * cell
                d.rectangle([x0, y0, x0 + cell - 2, y0 + cell - 2], fill=SIDE)
                col = SPAWN if (r, c) == s else TILE
                d.rectangle([x0 + 2, y0 + 2, x0 + cell - 5, y0 + cell - 5], fill=col)
        bx = ox + s[1] * cell + cell / 2; by = oy + s[0] * cell + cell / 2; rad = cell * 0.32
        d.ellipse([bx - rad, by - rad, bx + rad, by + rad], fill=BALL)
        d.text((idx * panel_w + pad, 6), title, fill=(200, 205, 214))
    img.save(out)
    print("wrote", out)


if __name__ == "__main__":
    project = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
    unity = os.environ.get(
        "UNITY_EDITOR",
        "/Applications/Unity/Hub/Editor/6000.5.1f1/Unity.app/Contents/MacOS/Unity")
    if "--extra-hard-extension" in sys.argv:
        execute_method = "PaintMaze.EditorTools.LevelBakeTool.BakeExtraHardExtension"
    elif "--extra-hard" in sys.argv:
        execute_method = "PaintMaze.EditorTools.LevelBakeTool.BakeExtraHardCatalogs"
    else:
        execute_method = "PaintMaze.EditorTools.LevelBakeTool.BakeAll"
    subprocess.run([
        unity, "-batchmode", "-nographics", "-quit",
        "-projectPath", project,
        "-executeMethod", execute_method,
        "-logFile", os.path.join(project, "build", "level-bake.log"),
    ], check=True)
